### ISSUE TITLE
部署volume时报错

### ISSUE THREAD

**Issue by bluezombiecn** [seaweedfs/seaweed-up#3]
CentOS Linux release 7.9.2009
kernel Version: 3.10.0-1160.45.1.el7.x86_64
lsblk Version:  util-linux 2.23.2

```
cat seaweed.yaml
......
# Server configs are used to specify the configuration of volume servers.
volume_servers:
  # The ip address of the volume server.
  - ip: 10.18.1.229
    port: 8382
    folders:
      - folder: /weed
        disk: ""
```

![image](https://user-images.githubusercontent.com/8877031/226275644-89ac6443-e58f-4597-a12d-3a71a4622d6f.png)

部署volume时显示lsblk错误，查询lsblk可以输出的列，发现缺少PATH,FSUSED这两个列导致报错。下图为lsblk可用列。
![image](https://user-images.githubusercontent.com/8877031/226277014-3cf0eb8d-fdce-4d67-afd5-45708d3e51f3.png)
